sudo: false
language: c

branches:
  except:
    - /^pr\..*/

env:
  global:
    # GITHUB_SECRET_TOKEN for Travis pushes
    secure: "RnDIN5dzw8UA/8NdwMFuSutuffQBmfbAC/AzmU7Una2QWvO8+dw30Ch35gF5b0l/NRRI1VudcSRBUt62goTUofikmUcqQcCnVkvHc1bWecIEYXto2lNWOFqpI2vyxzfLAa/mBNlm66Y0fa3vNLVtzjftAzTdMKYKUAxtwcElMQJjC76CN2uIZsy1JI5zawNrgF7D9HK0sqkkJZy2v4+kIFHHJeHVg4BnurlJfv/05Mv8ggDGgkONcNu5DDSuqgU1G1VMRqdJhZkUhtTNFuEZhphwk0HPNoaP3+ILt/ad/2caQEtaWP4csAJs2ugvmvSzbBiVPpQ5zC+s+nOaRIo+Gp8npiT5GFzU/rwTc215THt+REUlkz9DlREF1CTv3p6SS89LA9LAhXffuKSqRCAbk5pw0moVUgVxFqw6PKaK1yb4Xx7WXzBXPvz862N6teeoLtnmzu+awn74Eak6lhj+VBjhDQjeWHqC1PzUActnXBHvrG1CqiYL/AXzLla+elmkX9bTsGfE38b72hUCrsRL0Oa2cDmkSsXrjO17BXSYHlpFnBlqGW2DjNOCLM0powHrd1bAb9Auo7kStmFf5pXVj17/F0SmYUgEly19piLFojESGRbjyiMPJ6MdiwjppuC78aNVRnhBoBiUQUK6Pli1afH/xKYGQQ7XMVemA7aKPrA="

matrix:
  include:
    # Linux, gcc 6:
    - os: linux
      dist: trusty
      addons: &gcc6
        apt:
          packages:
            - gcc-6
            - python-pip
          sources:
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: DO_BENCH=0 COMPILER_NAME=gcc O_CC=gcc-6 BUILD_TYPE=RELEASE
    - os: linux
      dist: trusty
      addons: *gcc6
      compiler: gcc
      env: DO_BENCH=0 COMPILER_NAME=gcc O_CC=gcc-6 BUILD_TYPE=DEBUG

    # Linux, clang 3.8:
    - os: linux
      dist: trusty
      addons: &clang38
        apt:
          packages:
            - clang-3.8
            - python-pip
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      compiler: clang
      env: DO_BENCH=0 COMPILER_NAME=clang O_CC=clang-3.8 BUILD_TYPE=RELEASE
    - os: linux
      dist: trusty
      addons: *clang38
      compiler: clang
      env: DO_BENCH=0 COMPILER_NAME=clang O_CC=clang-3.8 BUILD_TYPE=DEBUG

    # Linux clang for benchmarking
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.8
            - python-pip
            - gnuplot
            - bc
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      compiler: clang
      env: DO_BENCH=1 COMPILER_NAME=clang O_CC=clang-3.8 BUILD_TYPE=RELEASE

    # Mac OS X, clang (default version):
    - os: osx
      compiler: clang
      env: DO_BENCH=0 COMPILER_NAME=clang O_CC=clang BUILD_TYPE=RELEASE
    - os: osx
      compiler: clang
      env: DO_BENCH=0 COMPILER_NAME=clang O_CC=clang BUILD_TYPE=DEBUG


cache:
  directories:
    - cache

install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      if [ "!" -x cache/cmake/bin/cmake ]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir -p cache/cmake
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cache/cmake
      fi
      export PATH="$TRAVIS_BUILD_DIR/cache/cmake/bin:$PATH"
    elif [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if "!" brew ls --version cmake; then
        brew install cmake
      fi
    fi

before_script:
  - uname -a
  - which cmake
  - cmake --version
  - echo $CC $COMPILER_NAME
  - which $CC
  - $CC --version

before_install:
  - pip install behave --user
  - export CC=$O_CC

script:
  - mkdir build
  - (cd build && cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..)
  - (cd build && cmake --build . --config "$BUILD_TYPE")
  - (if [ "${DO_BENCH}" == 2 ]; then cd build/tests; ./bench.sh; fi)

after_success:
  - chmod +x upload-generated-files.sh
  - |
    if [ "${DO_BENCH}" == 1 ]; then
      BRANCHES_TO_MERGE_REGEX='^feature/' \
      BRANCH_TO_MERGE_INTO=develop \
      GITHUB_REPO=nikkiom/tail \
        ./upload-generated-files.sh
    fi
